= Changelog
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

All `clj-otel-*` module versions are released in lockstep to Clojars.

`x.y.z` versions listed below do not follow semantic versioning.
Instead, development proceeds on a linear path where `z` increases for batches of incremental changes and `y` increases (with `z` reset to `0`) when milestones are reached.

Breaking changes will be documented here.

WARNING: Until version `1.0.0` there is a greater possibility of breaking changes, highlighted with [BREAK] below.

== `0.x` changes

=== `0.1.6` (in progress)

- Add support for Metrics API
- Add implementations of the following https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/http-metrics/[HTTP server metrics] for use by applications not run with the OpenTelemetry instrumentation agent:
* `http.server.active_requests`
* `http.server.duration`
* `http.server.request.size`
- [BREAK] The parameters for function `add-route-data!` have changed, there is a new parameter to specify the HTTP request method.
- [BREAK] The pattern for using `clj-otel` middleware and interceptors in applications has been revised.
The revised pattern uses new middleware `wrap-route`, `wrap-active-requests` and
`wrap-metrics-by-route` and interceptors `route-interceptor`, `active-requests-interceptor` and `metrics-by-route-interceptors` to capture matched routes in HTTP server spans and HTTP server metrics.
The pattern also ensures all requests are recorded, including those which do not match any route.
- New module `clj-otel-instrumentation-runtime-metrics` to provide access to JVM runtime metrics instrumentation for applications not using the OpenTelemetry instrumentation agent.
- Added aliases in examples
** `:metrics-*` to control export of metrics
** `:logging-*` to control application logging
- Bump deps:
* OpenTelemetry `1.25.0`
** [BREAK] When using autoconfiguration for a manually instrumented application, include the new JVM option `"-Dotel.java.global-autoconfigure.enabled=true"` or environment variable setting `OTEL_JAVA_GLOBAL_AUTOCONFIGURE_ENABLED=true`
** Methods to statically set the server host name attribute on server spans have been removed, as static data is better represented as an OpenTelemetry resource.
*** [BREAK] The function `add-server-name!` has been removed.
*** [BREAK] The option `:server-name` has been removed from the middleware and interceptors for server span support.
** [BREAK] Module `clj-otel-extension-aws` renamed to `clj-otel-contrib-aws-xray-propagator`
** [BREAK] Module `clj-otel-sdk-extension-aws` renamed to `clj-otel-contrib-aws-resources`
** [BREAK] Module `clj-otel-sdk-extension-resources` renamed to `clj-otel-instrumentation-resources`
* gRPC `1.54.0`
* Various build deps

=== `0.1.5` (2022-09-03)

- Bump deps:
* OpenTelemetry `1.17.0`
* gRPC `1.49.0`
* Various build deps

=== `0.1.4` (2022-07-05)

- Add support for including https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/span-general/#source-code-attributes[source code semantic attributes] when creating spans.
By default, attributes identifying the namespace, line number and source file path are included in spans created by `with-span!`, `with-span-binding`, and `async-span`.
- Update Pedestal HTTP server span support to always add route data to server spans
- Bump deps:
* OpenTelemetry `1.15.0`
** Modules `clj-otel-exporter-otlp-*` are merged to new module `clj-otel-exporter-otlp`
* gRPC `1.47.0`
* Various build deps

=== `0.1.3` (2022-05-22)

- Bump deps:
* OpenTelemetry `1.14.0`
* gRPC `1.46.0`
* Various build deps

=== `0.1.2` (2022-04-13)

- Include `ExceptionInfo` data as attributes in exception span events, by default
- Update examples to use namespaced attributes for spans and events
- Bump deps:
* OpenTelemetry `1.13.0`
** The default value for autoconfiguration property `otel.metrics.exporter` has changed from `none` to `otlp`
* Clojure `1.11.1`
* gRPC `1.45.1`
* Various build deps

=== `0.1.1` (2022-03-13)

- Bump deps:
* OpenTelemetry `1.12.0`
* gRPC `1.45.0`
* Various build deps

=== `0.1.0` (2022-02-27)

- Initial release
