= Changelog
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

All `clj-otel-*` module versions are released in lockstep to Clojars.

`x.y.z` versions listed below do not follow semantic versioning.
Instead, development proceeds on a linear path where `z` increases for batches of incremental changes and `y` increases (with `z` reset to `0`) when milestones are reached.

Breaking changes will be documented here.

WARNING: Until version `1.0.0` there is a greater possibility of breaking changes.

== `0.x` changes

=== `0.1.2` (in progress)

- Include `ExceptionInfo` data as attributes in exception span events, by default
- Update examples to use namespaced attributes for spans and events
- Bump gRPC deps to `1.45.1`
- Bump Clojure deps to `1.11.1`
- Bump various build deps

=== `0.1.1` (2022-03-13)

- Bump OpenTelemetry deps to `1.12.0`, gRPC deps to `1.45.0`
- Bump various build deps

=== `0.1.0` (2022-02-27)

- Initial release
