= Changelog
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

All `clj-otel-*` module versions are released in lockstep to Clojars.

`x.y.z` versions listed below do not follow semantic versioning.
Instead, development proceeds on a linear path where `z` increases for batches of incremental changes and `y` increases (with `z` reset to `0`) when milestones are reached.

Breaking changes will be documented here.

WARNING: Until version `1.0.0` there is a greater possibility of breaking changes.

== `0.x` changes

=== `0.1.3` (in progress)

- Bump deps:
* OpenTelemetry `1.14.0`
* gRPC `1.46.0`
* Various build deps

=== `0.1.2` (2022-04-13)

- Include `ExceptionInfo` data as attributes in exception span events, by default
- Update examples to use namespaced attributes for spans and events
- Bump deps:
* OpenTelemetry `1.13.0`
** The default value for autoconfiguration property `otel.metrics.exporter` has changed from `none` to `otlp`
* Clojure `1.11.1`
* gRPC `1.45.1`
* Various build deps

=== `0.1.1` (2022-03-13)

- Bump deps:
* OpenTelemetry `1.12.0`
* gRPC `1.45.0`
* Various build deps

=== `0.1.0` (2022-02-27)

- Initial release
