= Concepts
:toc:
:icons: font

== Observability, OpenTelemetry and `clj-otel`

=== What is observability?

*Observability* is the ability to measure a system's current state based on the *telemetry data* it generates, such as *traces*, *metrics*, *logs* and *events*.

An *observable system* may be *queried* to describe its *composition* and *behaviour*.
As systems are often highly distributed in nature, observability addresses the need to understand the behaviour with *context* across services, technologies and environments.

*Monitoring* is a complementary activity to observability, where typically a *dashboard* is configured to report predetermined *metrics* and *alerts* are set to trigger on specific conditions in the system.
Monitoring is oriented to detection of *known types of issues*, as the monitored metrics or conditions are determined in advance.

=== The goal of observability

*Observability* enables *detection and exploration of issues* as they occur and *assists with root cause analysis*.
By querying an observable system, *unexpected types of issue* can be detected, classified and monitored as they arise, addressing the problem of "unknown unknowns".
Questions on the actual behaviour of an observable system may be more readily answered:

* "What caused this failure?"
* "What caused this change in behaviour?"
* "Why do a particular user's requests fail?"
* "Is my latest canary deployment stable?"
* "Should I roll back the latest deployment?"
* "Are my intended performance improvements in the latest deployment working as expected?"
* "What uses my service, and what are the services it uses?"
* "What mix of request types are issued to the system?
Is that mix consistent across users?"
* "Which areas should I work on to improve experience for most users?"
* "How well is the system behaving for my premium users?"
* "What user segment suffers high response times and why?"
* "What is the biggest contributor to the system's poor performance?"
* "Why is the system's error rate worse than last month?
Are there new error cases?"
* "What is the cause of my service level indicators (SLIs) not meeting the service level objectives (SLOs)?"

Through *enhanced visibility* of system behaviour, observability *improves understanding* of the *impact of changes* made by developers and operators.

=== Introducing OpenTelemetry

https://opentelemetry.io/[OpenTelemetry] is a https://www.cncf.io/projects/[CNCF incubating project], formed after the merger of https://opentracing.io/[OpenTracing] and https://opencensus.io/[OpenCensus].

[quote,OpenTelemetry community]
OpenTelemetry's Mission: to enable effective observability by making high-quality, portable telemetry ubiquitousfootnote:[See https://github.com/open-telemetry/community/blob/main/mission-vision-values.md#mission-our-overall-north-star-as-a-community[OTel Mission, Vision And Values]].

OpenTelemetry is a set of APIs, SDKs, tooling, integrations and semantic conventions that are designed for the creation and management of telemetry data.
OpenTelemetry provides a vendor-agnostic implementation per language (Java, Go, JavaScript, C++ and others) that can be configured to export telemetry data to backends of your choice.
The Java implementation supports both *automatic instrumentation* of a large number of https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md[libraries, frameworks and application servers] and *manual instrumentation* of library or application source code.
OpenTelemetry supports various backends, including OSS projects (Jaeger, Zipkin, Prometheus, Grafana Tempo, SigNoz) and commercial products (Honeycomb, Lightstep, Aspecto, Dynatrace, New Relic, Datadog and more).

The OpenTelemetry project also provides the *OpenTelemetry Collector*, a vendor-agnostic deployable process which receives, processes and exports telemetry data.

=== OpenTelemetry status and adoption

Work on the OpenTelemetry specification and implementations is *in progress* by a *large community* of contributors.
Support for traces is the most mature, followed by metrics and then logs.
See https://opentelemetry.io/status/[a summary of OpenTelemetry status].

There is a growing consensus in the commercial monitoring and APM tools market to adopt OpenTelemetry as a *standard for telemetry in cloud native software*.
Many commercial products today offer ingest of OpenTelemetry trace data and support for metrics and logs is growing.
Several vendors have created their own *distributions* of the OpenTelemetry SDK and OpenTelemetry Collector, which are customisations tailored for use with their products.

=== What does this project `clj-otel` enable?

https://github.com/steffan-westcott/clj-otel[`clj-otel`] extends the reach of OpenTelemetry to *Clojure libraries and applications* by providing:

* A *small idiomatic Clojure API* that wraps the OpenTelemetry implementation for Java.
This enables manual instrumentation of Clojure libraries and applications using pure Clojure.
* *Ring middleware* and *Pedestal interceptors* for server span support.
* Support for creating spans around *asynchronous* Clojure code.
* A Clojure wrapper for *programmatic configuration* of the OpenTelemetry SDK.

https://github.com/steffan-westcott/clj-otel[`clj-otel`] is an umbrella project for several Clojure modules `clj-otel-*`.
They depend on the OpenTelemetry implementation for Java https://github.com/open-telemetry/opentelemetry-java[`opentelemetry-java`] and the OpenTelemetry instrumentation agent provided by https://github.com/open-telemetry/opentelemetry-java-instrumentation[`opentelemetry-java-instrumentation`].

== Supported telemetry backends

OpenTelemetry *exports* telemetry data to a variety of telemetry backends.
The choice of backend(s) is applied when configuring system components for deployment.

Query and presentation capabilities vary between backends.
Many backends predate OpenTelemetry and were conceived as solutions focussed on tracing, monitoring or application performance management (APM).
They have since been retrofitted to ingest telemetry data from OpenTelemetry.

The following sections are incomplete selections of open-source software (OSS) and commercial backends that accept telemetry data from OpenTelemetry.

=== OSS telemetry backends

* https://www.jaegertracing.io/[Jaeger]
* https://zipkin.io/[Zipkin]
* https://prometheus.io/[Prometheus]
* https://grafana.com/oss/tempo/[Grafana Tempo]
* https://signoz.io/[SigNoz]

=== Commercial telemetry backends

NOTE: Some commercial telemetry backends have a free version with a reduced capacity or feature set.

* https://www.honeycomb.io/[Honeycomb]
* https://lightstep.com/[Lightstep]
* https://www.dynatrace.com/[Dynatrace]
* https://newrelic.com/[New Relic]
* https://grafana.com/products/cloud/[Grafana Cloud]
* https://www.aspecto.io/[Aspecto]
* https://www.datadoghq.com/[Datadog]
* https://www.elastic.co/apm/[Elastic APM]
* https://www.splunk.com/en_us/observability.html[Splunk Observability Cloud]
* https://www.sumologic.com/[Sumo Logic]
* https://uptrace.dev/[Uptrace]
* https://www.appdynamics.com/[AppDynamics]
* https://www.instana.com/[Instana]
* https://aws.amazon.com/xray/[AWS X-Ray]
* https://cloud.google.com/trace[Google Cloud Trace]
* https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview[Azure Application Insights]
* https://docs.oracle.com/en-us/iaas/application-performance-monitoring/index.html[Oracle Cloud Infrastructure APM]
* https://tanzu.vmware.com/observability[VMWare Tanzu Observability]
* https://www.logicmonitor.com/[LogicMonitor]

== Using OpenTelemetry

The general workflow for using OpenTelemetry with your library or application is:

. Add instrumentation to your library or application such that it exports telemetry data.
. Configure system components to control how the telemetry data are processed and exported, either directly to telemetry backends or via OpenTelemetry Collector instance(s).
. Use telemetry backend features to explore system behaviour described by the telemetry data.

== Instrumenting libraries and applications

Instrumenting a library or application involves adding behaviour such that it exports telemetry data as it runs.

[#_automatic_instrumentation]
*Automatic instrumentation* achieves this by dynamically altering the library or application at runtime.
For the Java platform, automatic instrumentation is performed by the https://github.com/open-telemetry/opentelemetry-java-instrumentation[*OpenTelemetry instrumentation agent*], a Java agent that runs with the application.
Many https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md[libraries, frameworks and application servers] are supported by the agent out of the box.
For example, the agent will create server spans for requests received by a Jetty server, and client spans for requests issued by an Apache HttpClient instance.

[#_manual_instrumentation]
*Manual instrumentation* involves adding program code to the library or application at design time, using the OpenTelemetry API.
The `clj-otel-api` module in this project wraps the OpenTelemetry API for Java in an idiomatic Clojure facade.

IMPORTANT: Manual instrumentation program code depends on the OpenTelemetry API, never the OpenTelemetry SDK.

It is possible to combine automatic and manual instrumentation.
For example, attributes and events can be added using manual instrumentation to a span created by the agent, as well as adding extra spans.
This demonstrates manually enriching the telemetry data produced by an automatically instrumented application.

TIP: Make use of automatic instrumentation if possible for your application, as this is a quick way to get high quality telemetry with almost no effort.
Use manual instrumentation to enrich the telemetry data, or if your application does not use a framework supported by the agent.

== OpenTelemetry data model

In observability terms, *telemetry data* is an aggregation of data from four sources: traces, metrics, logs and events.
In the OpenTelemetry data model, these map onto traces, metrics and logs *data sources*.
Events are treated as a specific type of log, or captured as part of a trace.

[#_traces]
=== Traces

A trace represents the *flow of a single transaction* throughout the system.
A trace comprises a tree of *spans*, where a span represents a *unit of work* in a service and the parent-child relationship between the spans represent dependencies between them.
The *root span* of a trace typically describes the entire transaction and the other spans in the trace describe units of work performed as part of the transaction.
Traces provide causal *context* for system activity and can identify other telemetry data (metrics or logs) that are relevant.

Span data may include a name, *span kind*, attributes, start/end timestamps, links to other spans, a list of events and a status.

* The span name should identify a class of spans and not include data.
* The span kind indicates the relationship between the span and its parent and children in the trace.
The span kind is one of:
** `CLIENT` : Covers the client side of issuing a synchronous request, where the client side waits until a response is received.
** `SERVER` : Covers the server side of handling a synchronous request, where the remote client waits for a response.
** `PRODUCER` : Covers initiation of an asynchronous request, where the corresponding consumer span may start after the producer span ends.
** `CONSUMER` : Covers processing of an asynchronous producer request.
** `INTERNAL` : An internal operation within the local application or service.
* The events are timestamped records that may include attributes.
Exceptions thrown in a span's scope are captured as events.
* The status has a code `Ok` or `Error`, and in case of `Error` may also have a string description.

See specifications for https://opentelemetry.io/docs/reference/specification/trace/api/#span[span] and https://opentelemetry.io/docs/reference/specification/trace/api/#spankind[span kind].

=== Metrics

A metric is a numerical *measurement over a period of time*.
Metrics are used to indicate quantitative aspects of *system health*, such as resource (memory, disk, compute, network) usage, error rate, message queue length, and request response time.

=== Logs

A service log is made of *lines of text* (possibly structured e.g. in JSON format) written when certain *points in the service code are executed*.
Logs are well suited to ad-hoc debugging and capture of low-level details.

=== Events

Events are captured as either a specific type of log or as a span event.
Events are records that *describe actions taken* by the system over time, or *environmental changes* that occurred which are significant to the system, such as a service deployment or change in configuration.

[#_attributes]
=== Attributes

Attributes may be attached to some telemetry data such as spans and resources.
Attributes are a map where each entry has a string key and a value which is a boolean, long, double, string or an array of one of those types.
Attributes with `nil` values are dropped.

See the specification for https://opentelemetry.io/docs/reference/specification/common/common/#attributes[attributes] and https://opentelemetry.io/docs/reference/specification/common/attribute-naming/[attribute naming].

[#_resources]
=== Resources

A resource captures information about the entity for which telemetry data is recorded.
For example, information on the host and JVM version may be part of a resource.
Resources are included as part of other telemetry data such a traces and metrics.

The OpenTelemetry SDK contains resource implementations which capture a variety of host and process information.

=== Baggage

Baggage is mechanism for propagating telemetry metadata and is represented as a simple map.
It is intended as a means to add contextual information at a point in a transaction, to be read by a downstream service later in the same transaction and used as an element of telemetry data e.g. an attribute.
An example is to put a user identifier in the baggage to indicate the principal of a request.

[#_semantic_conventions]
== Semantic conventions

OpenTelemetry has defined a rich set of conventions for telemetry data.
This semantic unification across vendors and technologies promotes analysis of telemetry data created in heterogeneous, polyglot systems.
In particular, *semantic attributes* for spans and metrics are defined for common base technologies like HTTP, database, RPC, messaging, FaaS (Function as a Service) and others.
See https://opentelemetry.io/docs/concepts/glossary/#semantic-conventions[OpenTelemetry semantic conventions documentation].

`clj-otel` follows the semantic conventions for areas such as https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md[span exception events] and manually created https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md[HTTP client and server spans].

== Context

A context acts as an immutable map that holds values that are transmitted across API boundaries and threads.
A context may contain a span, baggage and possibly other values.
A new context is created from an existing context with the addition of a new key-value association.

[#_current_context]
=== Current context

The *current context* is a thread local `io.opentelemetry.context.Context` object.
It is used as a default for many functions in this project `clj-otel` and the underlying Java library `opentelemetry-java`.
The current context is safe to use when manually instrumenting synchronous code.

WARNING: The current context cannot be used when manually instrumenting asynchronous code.
See <<_instrumenting_asynchronous_clojure_code,Instrumenting asynchronous Clojure code>>.

[#_context_propagation]
=== Context propagation

Context propagation is the mechanism used to transmit context values across API boundaries and threads.
Context propagation enables traces to become *distributed traces*, joining clients to servers and producers to consumers.
In practice, this is achieved by injecting and extracting header values in HTTP requests using a *text map propagator*.

OpenTelemetry provides text map propagators for the following protocols:

* https://www.w3.org/TR/trace-context/[W3C Trace Context propagation protocol]
* https://www.w3.org/TR/baggage/[W3C baggage header propagation protocol]
* https://github.com/opentracing/basictracer-python/blob/master/basictracer/text_propagator.py[OpenTracing Basic Tracers protocol]
* Jaeger propagation protocol
* https://github.com/openzipkin/b3-propagation>openzipkin/b3-propagation[B3 propagation protocol]
* https://https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-tracingheader[AWS X-Ray Trace Header propagation protocol]

The *W3C Trace Context* and *W3C baggage header* propagation protocols are the most commonly used protocols for propagation of trace context and baggage.

[#_instrumenting_asynchronous_clojure_code]
== Instrumenting asynchronous Clojure code

When manually instrumenting asynchronous Clojure code with this library `clj-otel`, it is not possible to use the <<_current_context,current context>>.
This is because async Clojure function evaluations share threads, but each evaluation is associated with a distinct context.
The async function must instead maintain a reference to the associated context during evaluation, rather than use the current context.
Some functions in this library `clj-otel` take a `:context` or `:parent` option to indicate the associated context to use, as an alternative to the default current context.

== Trace sampling

*Sampling* is the process of selecting some elements from a set and deriving observations on the complete set based on analysis of those selected elements.
Sampling is a required technique when the volume of raw data is too high to analyse cost-effectively.

*Trace sampling* may be applied at any number of points between the instrumented application and the telemetry backend.
OpenTelemetry provides sampler implementations which may be applied in the application and/or the Collector.
Some telemetry backends may also apply sampling to trace data they receive, either automatically or with some developer intervention.

[#_exporters]
== Exporters

*Exporters* emit telemetry data to consumers, such as the Collector and telemetry backends.Exporters can be push or pull based.

== OpenTelemetry Protocol - OTLP

https://opentelemetry.io/docs/reference/specification/protocol/[OpenTelemetry Protocol (OTLP)] is the OpenTelemetry native protocol for encoding, transport and delivery of telemetry data.
OTLP is currently implemented over gRPC and HTTP transports.

Almost all telemetry backends that integrate with OpenTelemetry accept telemetry data in OTLP format.
An application or OpenTelemetry Collector exports data to these backends using an OTLP exporter.

== Using the OpenTelemetry SDK

The OpenTelemetry SDK implements the creation, sampling, batching and export of telemetry data.
The SDK acts as an implementation of the OpenTelemetry API.
For an application to export telemetry, the SDK and its dependencies need to be present and configured at runtime.

The SDK and its dependencies are added to an application in one of the following ways:

* [.underline]#By using the OpenTelemetry instrumentation agent#: In this option, the SDK and its dependencies are present but do not appear on the application classpath.
Also, autoconfiguration is used for configuring the SDK.
* [.underline]#By using the `opentelemetry-sdk-extension-autoconfigure` library as an application dependency#: This option is for autoconfiguration of the SDK where the OpenTelemetry instrumentation agent is not present.
The relevant optional SDK libraries (exporters, extensions, etc.) also need to be added as runtime dependencies.
* [.underline]#By adding the SDK as a compile-time dependency to the application#: This option is for programmatic configuration of the SDK.
The relevant optional SDK libraries also need to be added as compile-time dependencies.

If the SDK is not present at application runtime, all OpenTelemetry API calls default to a no-op implementation where no telemetry data is created.

=== Autoconfiguration

Autoconfiguration of the OpenTelemetry SDK refers to configuration using system properties or environment variables.
Configuration of the OpenTelemetry instrumentation agent uses the same mechanism.

See documentation for https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure[SDK autoconfiguration] and https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/agent-config.md[instrumentation agent configuration].

=== Programmatic configuration

The SDK can be programmatically configured, as an alternative to autoconfiguration.
This is a fallback option if autoconfiguration lacks the desired options.

This project `clj-otel` provides a module `clj-otel-sdk` for configuring the SDK in Clojure, as well as other support modules `clj-otel-exporter-\*`,`clj-otel-extension-*` and `clj-otel-sdk-extension-*` for programmatic access to various optional components.

== OpenTelemetry distros

An OpenTelemetry distro (or "distribution") supplied by a vendor is a repackaging of reference OpenTelemetry software, customised with the purpose of ease of use with the vendor's products.
They are not forks, in that they do not extend or change the OpenTelemetry API.

It is not a requirement to use a vendor's distro, it should always be possible to use the reference OpenTelemetry software and configure it as appropriate.
The obvious advantage to using a distro is ease of use, but a disadvantage is that sometimes the version of distro lags behind the reference OpenTelemetry version.

[#_opentelemetry_collector]
== OpenTelemetry Collector

The https://opentelemetry.io/docs/collector/[OpenTelemetry Collector] is a vendor-agnostic deployable process to manage telemetry data as it flows from instrumented applications to telemetry backends.
The Collector can transform telemetry data, for example insert or filter attributes.
It removes the need to run multiple, vendor-specific agents and collectors, when working with multiple telemetry data formats and telemetry backends.

It is not required to use the OpenTelemetry Collector, though its use is recommended to simplify telemetry data management in larger systems that have many instrumented services.
Some exporters provided by OpenTelemetry have default options set to target a Collector instance running on the same host.

== Alternative Clojure telemetry projects

The following are alternatives to OpenTelemetry in the Clojure ecosystem, which are concerned with the creation or processing of telemetry data.

=== Events & structured logs

* https://github.com/BrunoBonacci/mulog[μ/log] : Micro-logging library that logs events and data, not words
* https://github.com/amperity/ken[ken] : Observability library to instrument Clojure code
* https://github.com/henryw374/clojure.log4j2[clojure.log4j2] : Sugar for using https://logging.apache.org/log4j/2.x/[Log4j2] from clojure, including `MapMessage` support
* https://github.com/viesti/timbre-json-appender[timbre-json-appender] : Structured log appender for Timbre using jsonista
* https://github.com/logicblocks/cartus[cartus] : Structured logging abstraction with multiple backends
* https://cambium-clojure.github.io/[Cambium] : Structured logging for Clojure
* https://github.com/runejuhl/clj-journal[clj-journal] : Structured logging to systemd journal using native systemd libraries and JNA (Java Native Access)

=== Traces

* https://github.com/BrunoBonacci/mulog#%CE%BCtrace[μ/trace] : Micro distributed tracing library with the focus on tracking data with custom attributes; a subsystem of https://github.com/BrunoBonacci/mulog[μ/log]
* https://github.com/amperity/ken#tracing[ken] tracing support
* https://github.com/uswitch/opencensus-clojure[opencensus-clojure] : Clojure wrapper for https://github.com/census-instrumentation/opencensus-java[opencensus-java]
* https://github.com/alvinfrancis/opentracing-clj[opentracing-clj] : OpenTracing API support for Clojure, built on top of https://github.com/opentracing/opentracing-java[opentracing-java]
* https://github.com/Cyrik/omni-trace[omni-trace] : Clojure(Script) tracing for debugging

=== Unstructured logs

* https://github.com/ptaoussanis/timbre[Timbre] : Pure Clojure/Script logging library
* https://github.com/FundingCircle/clj-loga[clj-loga] : Custom log formatting for Timbre

=== Metrics

* https://riemann.io/[Riemann] : Network event stream processing system, in Clojure
* https://github.com/jitlogic/micrometer-clj[micrometer-clj] : Clojure wrapper for Java https://micrometer.io/[Micrometer] library
* https://github.com/metrics-clojure/metrics-clojure[metrics-clojure] : Clojure façade around https://metrics.dropwizard.io/[Dropwizard Metrics] library
* https://github.com/samsara/trackit[TRACKit!] : Clojure wrapper for https://metrics.dropwizard.io/[Dropwizard Metrics] library
* https://github.com/mrmcc3/aws-metrics-collector[aws-metrics-collector] : Clojure AWS Cloudwatch metric collector

=== Monitoring

* https://github.com/logicblocks/salutem[salutem] : Health check library
* https://github.com/sereno-xyz/sereno[sereno] : Uptime monitoring application
* https://github.com/bass3m/plumon[plumon] : Clojure monitoring service with pluggable monitorables