= Guides
:toc:
:toclevels: 3

== Add telemetry to your library or an application

=== Add automatic instrumentation when running an application

Follow the guide to <<_run_with_the_opentelemetry_auto_instrumentation_agent,run the application with the OpenTelemetry instrumentation agent>>.

=== Add manual instrumentation to your library or application code

==== Add instrumentation API project dependency

==== Create a span for a synchronous process

==== Create a span for an asynchronous process

==== Add attributes to a span

==== Add an event to a span

==== Add an exception to a span

=== Work with HTTP client and server spans

==== Use Ring middleware for server spans

==== Use Pedestal interceptors for server spans

==== Add route data to a server span

==== Add HTTP response data to a client or server span

== Configure and run an application with telemetry

Select one of these options and follow the linked guide:

* <<_run_with_the_opentelemetry_auto_instrumentation_agent,Run with the OpenTelemetry auto-instrumentation agent>> : Select this option to add automatic instrumentation to the application as it runs.
Manual instrumentation may optionally be added.
* <<_run_with_autoconfigured_sdk,Run with autoconfigured SDK>> : Select this option to add manual instrumentation only, without automatic instrumentation; The SDK will be configured using properties or environment variables.
* <<_run_with_programmatically_configured_sdk,Run with programmatically configured SDK>> : Select this option to add manual instrumentation only, without automatic instrumentation; The SDK will be configured programmatically in the application.

[#_run_with_the_opentelemetry_auto_instrumentation_agent]
=== Run with the OpenTelemetry auto-instrumentation agent

* Download the https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar[latest version of the OpenTelemetry instrumentation agent JAR].
The agent JAR includes the SDK and all its dependencies.
* Configure the agent and SDK, using properties.
See the https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/agent-config.md[agent and SDK configuration documentation].
* When running the application, enable the agent with the `-javaagent` JVM flag.
A minimal configuration includes the service name of the application.
For example, with `deps.edn` use an alias like the following:

.`deps.edn`
[source,clojure]
----
{;; ...
 :aliases {
   :auto-instrument {:jvm-opts ["-javaagent:path/to/opentelemetry-javaagent.jar"
                                "-Dotel.resource.attributes=service.name=my-app"]}}}
----

[#_run_with_autoconfigured_sdk]
=== Run with autoconfigured SDK
* Configure the SDK using properties and environment variables. See https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure[SDK autoconfigure configuration documentation].

.`deps.edn`
[source,clojure]
----
{;; ...
 :aliases {
   :otel {:jvm-opts ["-Dotel.resource.attributes=service.name=example-app"]
          :extra-deps {io.opentelemetry/opentelemetry-sdk-extension-autoconfigure {:mvn/version "1.9.1-alpha"}
                       io.opentelemetry/opentelemetry-sdk-extension-resources {:mvn/version "1.9.1"}}}}}
----

[#_run_with_programmatically_configured_sdk]
=== Run with programmatically configured SDK

.`deps.edn`
[source,clojure]
----
{;; ...
 :deps {com.github.steffan-westcott/clj-otel-sdk                     {:mvn/version "0.1.0-SNAPSHOT"}
        com.github.steffan-westcott/clj-otel-sdk-extension-resources {:mvn/version "0.1.0-SNAPSHOT"}}}
----

=== Mute telemetry signals

=== Batch spans prior to export

=== Export spans to the OpenTelemetry Collector

=== Export spans directly to backends

==== Export spans directly to backends that support OTLP

==== Export spans directly to Jaeger

==== Export spans directly to Zipkin

== Use the OpenTelemetry Collector

=== Deploy the OpenTelemetry Collector

=== Configure the OpenTelemetry Collector