{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 } },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 5, "y": 0 },
   "targets": [
    { "limit": 20, "query": "{}", "tableType": "traces" }
   ]
  },
  {
   "title": "Service graph",
   "type": "nodeGraph",
   "gridPos": { "h": 20, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "limit": 20, "tableType": "traces" }
   ]
  },
  {
   "title": "Average requests",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{service_name=\"average-service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"GET /average\",status_code!=\"STATUS_CODE_ERROR\"}[$__rate_interval]))",
     "legendFormat": "ok"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{service_name=\"average-service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"GET /average\",status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Average request rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{service_name=\"average-service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"GET /average\"}[$__rate_interval]))",
     "legendFormat": "average request rate"
    }
   ]
  },
  {
   "title": "Service instance availability",
   "type": "status-history",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\",span_name=\"GET /ping\"} > bool traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\",span_name=\"GET /ping\"} offset 15s)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(traces_span_metrics_duration_seconds_sum{service_name=\"average-service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"GET /average\"}[$__rate_interval]))) / (sum(rate(traces_span_metrics_duration_seconds_count{service_name=\"average-service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"GET /average\"}[$__rate_interval])))",
     "legendFormat": "average request duration"
    }
   ]
  }
 ]
}