{
 "title": "HTTP server routes",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,job)"
    }
   },
   {
    "name": "server_span",
    "label": "route",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$service\"},span_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Route requests - $server_span", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server_span" },
  {
   "title": "Route request rate - $server_span",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_response_status_code) (rate(traces_span_metrics_calls_total{service_name=\"$service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"$server_span\"}[$__rate_interval]))",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Route request rate - $server_span",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{service_name=\"$service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"$server_span\"}[$__rate_interval]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Route request duration - $server_span",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (http_response_status_code) (rate(traces_span_metrics_duration_seconds_sum{service_name=\"$service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"$server_span\"}[$__rate_interval])) / (sum by (http_response_status_code) (rate(traces_span_metrics_duration_seconds_count{service_name=\"$service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"$server_span\"}[$__rate_interval]))))",
     "legendFormat": "{{http_response_status_code}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(traces_span_metrics_duration_seconds_bucket{service_name=\"$service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"$server_span\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "(sum(rate(traces_span_metrics_duration_seconds_sum{service_name=\"$service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"$server_span\"}[$__rate_interval]))) / (sum(rate(traces_span_metrics_duration_seconds_count{service_name=\"$service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"$server_span\"}[$__rate_interval])))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Route request duration - $server_span",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(traces_span_metrics_duration_seconds_sum{service_name=\"$service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"$server_span\"}[$__rate_interval]))) / (sum(rate(traces_span_metrics_duration_seconds_count{service_name=\"$service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"$server_span\"}[$__rate_interval])))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Route request rate - $server_span",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (rate(traces_span_metrics_duration_seconds_count{service_name=\"$service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"$server_span\"}[$__rate_interval]))",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Route request duration - $server_span",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_seconds_bucket{service_name=\"$service\",span_kind=\"SPAN_KIND_SERVER\",span_name=\"$server_span\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "limit": 20,
     "query": "{resource.service.name=\"$service\" && kind=server && name=\"$server_span\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}