{
 "title": "HTTP server instances",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({job=\"$service\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All routes request rate",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (rate(http_server_request_duration_seconds_count{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "All routes request rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "All routes request duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (http_response_status_code) (rate(http_server_request_duration_seconds_sum{instance=\"$instance\"}[$__rate_interval])) / (sum by (http_response_status_code) (rate(http_server_request_duration_seconds_count{instance=\"$instance\"}[$__rate_interval]))))",
     "legendFormat": "{{http_response_status_code}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_server_request_duration_seconds_bucket{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_sum{instance=\"$instance\"}[$__rate_interval]))) / (sum(rate(http_server_request_duration_seconds_count{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "All routes request duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_sum{instance=\"$instance\"}[$__rate_interval]))) / (sum(rate(http_server_request_duration_seconds_count{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "All routes request rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (rate(http_server_request_duration_seconds_count{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "All routes request duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_server_request_duration_seconds_bucket{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "limit": 20,
     "query": "{resource.service.instance.id=\"$instance\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{service_instance_id=\"$instance\"}"
    }
   ]
  }
 ]
}