{
 "title": "JVM",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values({job=\"$service\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "JVM Heap Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\",jvm_memory_type=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{instance=\"$instance\",jvm_memory_type=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_limit_bytes{instance=\"$instance\",jvm_memory_type=\"heap\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "G1 Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\",jvm_memory_pool_name=\"G1 Eden Space\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\",jvm_memory_pool_name=\"G1 Eden Space\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "G1 Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\",jvm_memory_pool_name=\"G1 Survivor Space\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\",jvm_memory_pool_name=\"G1 Survivor Space\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "G1 Old Gen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\",jvm_memory_pool_name=\"G1 Old Gen\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\",jvm_memory_pool_name=\"G1 Old Gen\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_limit_bytes{instance=\"$instance\",jvm_memory_pool_name=\"G1 Old Gen\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(jvm_gc_duration_seconds_sum{instance=\"$instance\"}) - (jvm_gc_duration_seconds_sum{instance=\"$instance\"} offset 15s)",
     "legendFormat": "{{jvm_gc_action}}"
    }
   ]
  },
  {
   "title": "JVM Non-Heap Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non-Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\",jvm_memory_type=\"non_heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=\"$instance\",jvm_memory_type=\"non_heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_limit_bytes{instance=\"$instance\",jvm_memory_type=\"non_heap\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CodeHeap 'non-profiled nmethods'",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\",jvm_memory_pool_name=\"CodeHeap 'non-profiled nmethods'\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\",jvm_memory_pool_name=\"CodeHeap 'non-profiled nmethods'\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_limit_bytes{instance=\"$instance\",jvm_memory_pool_name=\"CodeHeap 'non-profiled nmethods'\"}",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CodeHeap 'profiled nmethods'",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\",jvm_memory_pool_name=\"CodeHeap 'profiled nmethods'\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\",jvm_memory_pool_name=\"CodeHeap 'profiled nmethods'\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_limit_bytes{instance=\"$instance\",jvm_memory_pool_name=\"CodeHeap 'profiled nmethods'\"}",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Compressed Class Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\",jvm_memory_pool_name=\"Compressed Class Space\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\",jvm_memory_pool_name=\"Compressed Class Space\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_limit_bytes{instance=\"$instance\",jvm_memory_pool_name=\"Compressed Class Space\"}",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CodeHeap 'non-nmethods'",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\",jvm_memory_pool_name=\"CodeHeap 'non-nmethods'\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\",jvm_memory_pool_name=\"CodeHeap 'non-nmethods'\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_limit_bytes{instance=\"$instance\",jvm_memory_pool_name=\"CodeHeap 'non-nmethods'\"}",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\",jvm_memory_pool_name=\"Metaspace\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\",jvm_memory_pool_name=\"Metaspace\"}",
       "legendFormat": "committed"
      }
     ]
    },
    {
     "title": "Loaded Classes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jvm_class_count{instance=\"$instance\"}",
       "legendFormat": "current"
      },
      {
       "expr": "jvm_class_loaded_total{instance=\"$instance\"}",
       "legendFormat": "since JVM start"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non-Daemon Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jvm_thread_count{instance=\"$instance\",jvm_thread_daemon=\"false\"}",
       "legendFormat": "{{jvm_thread_state}}"
      }
     ]
    },
    {
     "title": "Daemon Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "targets": [
      {
       "expr": "jvm_thread_count{instance=\"$instance\",jvm_thread_daemon=\"true\"}",
       "legendFormat": "{{jvm_thread_state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "jvm_cpu_recent_utilization_ratio{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}